<?php

namespace ContainerM8YFqzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EKzrD0rService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EKzrD0r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EKzrD0r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationManager' => ['privates', 'security.authentication.manager', 'getSecurity_Authentication_ManagerService', true],
            'customerRepository' => ['privates', 'Eccube\\Repository\\CustomerRepository', 'getCustomerRepositoryService', true],
            'tokenStorage' => ['services', '.container.private.security.token_storage', 'get_Container_Private_Security_TokenStorageService', false],
        ], [
            'authenticationManager' => '?',
            'customerRepository' => 'Eccube\\Repository\\CustomerRepository',
            'tokenStorage' => '?',
        ]);
    }
}
