<?php

namespace ContainerM8YFqzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyFormRepositoryService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private 'Customize\Repository\MyFormRepository' shared autowired service.
     *
     * @return \Customize\Repository\MyFormRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Customize'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'MyFormRepository.php';

        return $container->privates['Customize\\Repository\\MyFormRepository'] = new \Customize\Repository\MyFormRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
