<?php

namespace ContainerM8YFqzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrefectureControllerService extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the public 'Customize\Controller\PrefectureController' shared autowired service.
     *
     * @return \Customize\Controller\PrefectureController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Customize'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'DatabaseConnectionController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'app'.\DIRECTORY_SEPARATOR.'Customize'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PrefectureController.php';

        return $container->services['Customize\\Controller\\PrefectureController'] = new \Customize\Controller\PrefectureController();
    }
}
