<?php

namespace ContainerM8YFqzL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduct3Service extends Eccube_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mdQTIqb.Eccube\Entity\Product' shared service.
     *
     * @return \Eccube\Entity\Product
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mdQTIqb": it references class "Eccube\\Entity\\Product" but no such service exists.');
    }
}
