monolog:
    handlers:
        buffered:
            type:     buffer
            handler:  'null_handler'
            channels: ["!event"]
            level:    debug
        'null_handler':
            type: 'null'
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']

services:
    easycorp.easylog.handler:
        class: EasyCorp\EasyLog\EasyLogHandler
        public: false
        arguments:
            - '/dev/null'  # This can be left as it won't be used with null handler
