monolog:
    handlers:
        e_user_deprecated_filter:
            type: filter
            accepted_levels: ['info']
            channels: ['php']
            handler: blackhole
            bubble: false
        main:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: blackhole
        front:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: blackhole
            channels: ['front', 'app', 'php']
        admin:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: blackhole
            channels: ['admin', 'app', 'php']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
        # keep this last
        blackhole:
            type: "null"

# Remove the definitions of rotating file handlers as they are not used anymore
# main_rotating_file, front_rotating_file, and admin_rotating_file removed
