<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerZMAxxFf\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZMAxxFf/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZMAxxFf.legacy');
=======
if (\class_exists(\Container6NKFqB7\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6NKFqB7/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6NKFqB7.legacy');
>>>>>>> Aunik

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerZMAxxFf\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \ContainerZMAxxFf\Eccube_KernelDevDebugContainer([
    'container.build_hash' => 'ZMAxxFf',
    'container.build_id' => '4c81624d',
    'container.build_time' => 1716200794,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZMAxxFf');
=======
    \class_alias(\Container6NKFqB7\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \Container6NKFqB7\Eccube_KernelDevDebugContainer([
    'container.build_hash' => '6NKFqB7',
    'container.build_id' => '1940714b',
    'container.build_time' => 1716193521,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6NKFqB7');
>>>>>>> Aunik
