<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6NKFqB7\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6NKFqB7/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6NKFqB7.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6NKFqB7\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \Container6NKFqB7\Eccube_KernelDevDebugContainer([
    'container.build_hash' => '6NKFqB7',
    'container.build_id' => '1940714b',
    'container.build_time' => 1716193521,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6NKFqB7');
