<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM8YFqzL\Eccube_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM8YFqzL/Eccube_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM8YFqzL.legacy');

    return;
}

if (!\class_exists(Eccube_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM8YFqzL\Eccube_KernelDevDebugContainer::class, Eccube_KernelDevDebugContainer::class, false);
}

return new \ContainerM8YFqzL\Eccube_KernelDevDebugContainer([
    'container.build_hash' => 'M8YFqzL',
    'container.build_id' => 'a7ca013f',
    'container.build_time' => 1716185811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM8YFqzL');
